### PR TITLE
for ch-004 ch-1.pl

### PR DESCRIPTION
**Pull request by dmanto**
My solution to challenge-004 1
Based on the fact that a circle with radious N will have an area of π x N²
No square roots, no divisions until the very end, so is easier to estimate precision.
Relatively slow though :(

### CODE REVIEW

**Comment by manwar** [comment]
@dmanto, it seems you misread the question. The challenge is the total number of PI digits should be same as size of your perl script. So if your perl script size is 10 bytes then the very same perl script should print 10 PI digits.

**Comment by dmanto** [comment]
Oooops I thought script size was in lines :). So eight lines meant eight decimal places...
Sorry about that, I will think of some solution and come back...

**Comment by manwar** [comment]
All the best :-)

**Comment by dmanto** [comment]
please check this solution.
It's a 375 bytes perl 5 script that produces a 375 decimal places pi.
Hope this one is ok,
BR,

**Comment by manwar** [comment]
Unique solution so far and it blew my mind initially.
Thanks @dmanto

**Pull request merged**
