### PR TITLE
PWC Week 2, Challenge 1

### PR DESCRIPTION
**Pull request by ofperfection**

### CODE REVIEW

**Comment by manwar** [comment]
Thanks for sharing the solution. 
Can you please rename the script to ch-1.p6 to be consistent with others?

We follow the naming convention like:

ch-1.sh
ch-1.pl
ch-1.p6

or 

ch-2.sh
ch-2.pl
ch-2.p6

Best Regards,
Team PWC

**Comment by manwar** [comment]
Well done :-)

**Comment by ofperfection** [comment]
Script renamed!

**Comment by manwar** [comment]
Thanks for your contributions.

**Pull request merged**
