### PR TITLE
rjt's Week 048 solutions and blogs

### PR DESCRIPTION
**Pull request by rjt-pl**

### CODE REVIEW

**Comment by rjt-pl** [comment]
Thanks Holli! I used a circular linked list (implemented with the `@ll` array, where the array index is the "person number", and the value is the "next" pointer). The circular linked list "delete" operation is exactly the same as "killing" a person with the sword, and the "next" operation is like passing the sword to the next person. The `$cur` (cursor) variable is that sword.

[My blog post](http://www.ry.ca/2020/02/survivor-josepheus-problem/) has some diagrams and more discussion.

**Comment by holli-holzer** [comment]
Yeah, no. That ain't no linked list, that's more black magic (Haven't read the blog yet). This is a linked list =): 

```
role Concatenationem { has $.vicinus is rw; }
class Moribunda is Int does Concatenationem { };

sub bicimare-sine-fine( Int $homines where * > 1 ) 
{
    my $armis = my $primus = Moribunda.new(1);

    for 2..$homines
    { 
        my $homine = Moribunda.new($_); 
        $armis.vicinus = $homine; 
        $armis = $homine; 
    }
    
    $armis = $armis.vicinus = $primus;

    while $armis != $armis.vicinus 
    {
        $armis = $armis.vicinus = $armis.vicinus.vicinus;
    }

    $armis;
}

say bicimare-sine-fine( 50 );
```

**Comment by manwar** [comment]
Thanks @rjt-pl

**Comment by rjt-pl** [comment]
Ha! Forgive me, @holli-holzer; when I learned system programming, black magic was standard operating procedure.

Looking at your linked list code, our solutions are algorithmically identical, but I used an array of Ints for an underlying representation, whereas you used Raku's memory management, object pointers, inheritance, and garbage collection. Wait a minute! Your solution might just have more black magic going on than mine. :-)

One thing is for sure, though: your identifier names are way more fun than mine.

**Comment by manwar** [comment]
@rjt-pl @holli-holzer 
I am really enjoying the technical discussion here. It is great that we review each others work.

**Pull request merged**
