### PR TITLE
Solution submission weekly challenge (#2)

### PR DESCRIPTION
**Pull request by ohmycloud**

### CODE REVIEW

**Comment by manwar** [comment]
Thanks @ohmycloud for your contributions. 
Shall I add you to the team? What name would you prefer?

**Comment by ohmycloud** [comment]
@manwar Thank you. Just use `ohmycloud` as name is okay.

**Comment by manwar** [comment]
OK, I will use "ohmycloud" here but on the team page, I will use "Chenyf". Is that OK?

**Comment by ohmycloud** [comment]
@manwar Yes, Thank you very much.

**Comment by manwar** [comment]
Thanks @ohmycloud

**Pull request merged**
