### PR TITLE
Solution challenge-001 andrezgz

### PR DESCRIPTION
**Pull request by andrezgz**
Hi Mohammad. Is it possible to add my resolution for the first challenge now?

### CODE REVIEW

**Comment by manwar** [comment]
@andrezgz, yes you can.
Just curious are you a member already?
If not, what name would like us to use on the team page?
I am unable to make out from your github username.

**Comment by andrezgz** [comment]
@manwar, I'm not a member. Andrezgz is ok, if you don't mind.

**Comment by manwar** [comment]
Perfect, I will add you to the team.

**Comment by manwar** [comment]
Thanks @andrezgz

**Pull request merged**
