### PR TITLE
add solution week 138 task 1 in perl and blog

### PR DESCRIPTION
**Pull request by oWnOIzRi**

### CODE REVIEW

**Comment by manwar** [comment]
Thanks @oWnOIzRi

**Comment by oWnOIzRi** [comment]
@manwar weirdly my python guest contribution hasn't shown up on the website charts.  Did I do something wrong there?

**Comment by manwar** [comment]
> @manwar weirdly my python guest contribution hasn't shown up on the website charts. Did I do something wrong there?

My mistake, I missed it. 
I have updated charts.

Thanks @oWnOIzRi

**Comment by oWnOIzRi** [comment]
thanks @manwar , I appreciate it.

**Pull request merged**
