### PR TITLE
Week 292 - Fund the biggest and clear the balls

### PR DESCRIPTION
**Pull request by pjcs00**

### CODE REVIEW

**Comment by manwar** [comment]
@pjcs00 did you close by mistake?

**Comment by pjcs00** [comment]
Probably. I'll try again.

Peter

**Comment by pjcs00** [comment]
I'm hoping that's done it now.

Peter

*--*
*Peter Campbell Smith*
***@***.***
07599 992350

**Comment by manwar** [comment]
@pjcs00 all good now, thanks.

**Pull request closed without merging**
