### PR TITLE
the task 1 and task 2 of 267_challenge is completed by princy

### PR DESCRIPTION
**Pull request by princyym**
i have done task1 and task2 of 276 challenge no. by princy

### CODE REVIEW

**Comment by manwar** [comment]
Pleasantly surprised by your interest. Thanks @princyym

**Comment by manwar** [comment]
@princyym I only see task 1. The task 2 is empty file.

**Comment by manwar** [comment]
@princyym Also just for future reference, please follow the directory structure as below

         challenge-<week> / princy-perl / perl / ch-1.pl
         challenge-<week> / princy-perl / perl / ch-2.pl

Thanks

**Comment by princyym** [comment]
Sure @manwar , I will look into the task and follow the same structure as above suggested

**Pull request merged**
