### PR TITLE
Bring on the bonus challenges

### PR DESCRIPTION
**Pull request by Scimon**

### CODE REVIEW

**Comment by manwar** [comment]
I feel stupid not doing it myself :-(
I am finding it hard to match your speed and thought process.
Thanks @Scimon

**Comment by Scimon** [comment]
Don't worry about it, anyway I thought about it last night so I just had to implement it this morning ;)

**Comment by Scimon** [comment]
It's not a race, it's a challenge and we are each accepting the challenge at our own levels and pace. 

Heck I couldn't keep up this level of commitment to running it, you have all my admiration for that.

**Comment by manwar** [comment]
Thanks for the encouraging words, means a lot.
Luckily all the contributions are saved so that I can go back and play with it later.

**Pull request merged**
