### PR TITLE
Branch for challenge 263

### PR DESCRIPTION
**Pull request by princyym**
tha challenge is done #263 by princy

### CODE REVIEW

**Comment by jo-37** [comment]
Hi Princy,
it looks like your PR doesn't match the site's directory structure. It should be `<challenge>/<user>/<lang>/ch-<n>.<ext>,` whereas yours is `<challenge>/<user>-<lang>/ch-<n>.<ext>`.
Best regards,
🐻

**Comment by manwar** [comment]
@jo-37 if I an not mistaken this pull request was submitted because of confusion. @princyym was one of the participant of Outreachy program. As a part of initial contribution period, she submitted the pull request thinking this contribution would be eligible for Outreachy program. Unfortunately it is not, instead we have separate repository for this program: https://github.com/ChallengeForge/TheWeeklyChallenge

**Comment by manwar** [comment]
Welcome on board and thanks for your contributions. @princyym

**Comment by princyym** [comment]
hello @manwar I want to contribute to Outreachy labeled issues such as "Create badge icon #146", can you guide me related to this? 
I am confused related to:
 1. Do I have to design using Figma?
2. Do I have to code for this or are the templates required. 
 It would be helpful and I am looking for a positive response.

**Comment by manwar** [comment]
@princyym Happy to see you want to contribute to The Weekly Challenge project for Outreachy.  This issue is already taken care by Himanshi. Srestha.

https://github.com/manwar/theweeklychallenge/issues/146

I would suggest you join us on Slack channel where you can discuss the subject with other members of the team. Please share your email with us at mohammad.anwar@yahoo.com. I will then send you the invite.

Looking forward to work with you.

**Comment by princyym** [comment]
Thanks for the response, I will surely be active on slack and looking forward to contributing to issues. @manwar

**Pull request merged**
