### PR TITLE
added impossibility check

### PR DESCRIPTION
**Pull request by holli-holzer**

### CODE REVIEW

**Comment by manwar** [comment]
Thanks @holli-holzer

**Comment by xkr47** [comment]
Hi,
Out of interest I had to try your version, but found some funnies:
* for 995 your version reports 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110 but I get 1110000110 (= 1115578 * 995)
* for 98 your version reports `Impossible` but I get `11000010` (= 112245 * 98)
All my numbers are in base 10.

**Comment by holli-holzer** [comment]
Yes, I just realised it's buggy.

Try 
```
say (1 .. Inf).map( *.base(2).Str ).first( * %% $n );
```

**Comment by xkr47** [comment]
It works for my tests.. and it's faaast! :)

**Comment by xkr47** [comment]
btw, `base(2)` already returns `Str`

**Comment by holli-holzer** [comment]
That's true. The optimizer will magicwand that away. 
I figured I leave it in to make it clear we have a string of 1s and 0s.

**Pull request merged**
