### PR TITLE
Challenge 44

### PR DESCRIPTION
**Pull request by jacoby**
I hope your father is feeling better.

### CODE REVIEW

**Comment by holli-holzer** [comment]
You have duplicate solutions in #1

**Comment by jacoby** [comment]
@holli-holzer holli-holzer I don't see how that's possible, but I'll try again when I'm on that computer again.

**Comment by jacoby** [comment]
Went recursive to solve the issue.

**Comment by manwar** [comment]
Dad is doing well and back home.
Thanks @jacoby

**Pull request merged**
