### PR TITLE
challenge 297

### PR DESCRIPTION
**Pull request by pme**
- **Challenge 296 Task 1 and 2 solutions in Perl by Matthias Muth - Update**
- **Challenge 297 Solutions (Raku)**
- **challenge 295, raku solutions**
- **challenge 296, raku solutions**
- **challenge 149, raku solutions**
- **challenge 297, raku solutions**
- **Solve 297: Contiguous Array & Semi-Ordered Permutation by E. Choroba**
- **PWC 297**
- **Solve PWC297-2**
- **Add PWC297-1**
- **Change the error message**
- **Filter on list lengths**
- **Week 297**
- **:sparkles: Week 297 in BQN**
- **- Added solutions by Eric Cheung. - Added solutions by Mark Anderson. - Added solutions by Feng Chang. - Added solutions by E. Choroba. - Added solutions by Luca Ferrari. - Added solutions by Peter Meszaros. - Added solutions by W. Luis Mochan. - Added solutions by Conor Hoekstra. - Added solutions by David Ferrone.**
- **Robbie Hatley's solutions, in Perl, for The Weekly Challenge #297.**
- **- Added solutions by Robbie Hatley.**
- **RogerBW solutions for challenge no. 297**
- **Add Peter Pentchev's Rust solutions to 297**
- **Week 297 - Room 101 and pretunatmios**
- **- Added solutions by Peter Pentchev. - Added solutions by Peter Campbell Smith. - Added solutions by Roger Bell_West.**
- **- Added solutions by Ulrich Rieke.**
- **DAJ 297**
- **Challenge 297 by Jaldhar H. Vyas.**
- **new file:   challenge-297/mattneleigh/perl/ch-1.pl new file:   challenge-297/mattneleigh/perl/ch-2.pl**
- **Challenge 297 LK Perl Python**
- **Add solutions by Dorian 'vxern' Oszczęda.**
- **- Added solutions by Dave Jacoby. - Added solutions by Jaldhar H. Vyas. - Added solutions by Matthew Neleigh. - Added solutions by Lubos Kolouch. - Added solutions by Dorian Mateusz Oszczeda.**
- **- Tidied up contributions.**
- **- Updated guest name.**
- **:sparkles: Week 76 in BQN**
- **DAJ 297b**
- **- Added solutions by Conor Hoekstra. - Added solutions by Dave Jacoby.**
- **Perl & Raku solutions to Tasks 1 & 2 for Week 297**
- **Solution to task 1**
- **Solution to task 2**
- **Blog for challenge 297**
- **- Added solutions by Athanasius. - Added solutions by Jorg Sommrey.**
- **297**
- **- Added solutions by Robert Ransbottom.**
- **challenge-297**

### CODE REVIEW

**Comment by manwar** [comment]
@pme This pull request has serious  conflicts. Can you please take a look? If you point me to a real change then I can manually update rather merging this.

**Comment by pme** [comment]
Hi Mohammad,
You can find my change following the link right above your comment. e3d3def
-
https://github.com/manwar/perlweeklychallenge-club/pull/11240/commits/e3d3def1a25a9fcb0e9dfd34ed7b4dbe1694c011

I sent a pull request with different content from the same branch
(challenge-297) in the beginning of this week. Shouldn't I have rebased my
branch to the master before committing and creating new pull request?

[image: image.png]

Regards

**Comment by manwar** [comment]
@pme Merged your changes manually, thanks.
It is always good idea to rebase before adding new changes.

**Comment by pme** [comment]
Thanks a lot!

**Pull request closed without merging**
