### PR TITLE
initial

### PR DESCRIPTION
**Pull request by andemark**

### CODE REVIEW

**Comment by stuart-little** [comment]
@andemark I believe your `ch-1` script doesn't check whether the two strings have the same length, and the zip simply cuts off the tail of the longest.

So `abca` and `xyz` register as isomorphic (I've tried) even though they're not..

**Comment by andemark** [comment]
> @andemark I believe your `ch-1` script doesn't check whether the two strings have the same length, and the zip simply cuts off the tail of the longest.
> 
> So `abca` and `xyz` register as isomorphic (I've tried) even though they're not..

Thanks for pointing that out, Stuart. I think it's all working now :)

**Comment by stuart-little** [comment]
Sure looks good to me :).

**Comment by manwar** [comment]
Thanks @andemark

**Pull request merged**
