### PR TITLE
contributions from jaredor

### PR DESCRIPTION
**Pull request by jaredor**

### CODE REVIEW

**Comment by jaredor** [comment]
Manwar, I don't know what happened. I tried to push my one-line change in the blogs.txt file into my repository and I got a lot of chatter back from git about how I was being refused because my repo was out-of-date and hints were given about what I had to do. So I followed the hints and git stopped chattering at me, but now I see that I have a lot of other people's changes to this repository in my pull request instead of my single file change.

I know this is a result of my limitation of skill with git, but I absolutely do not care about maintaining everyone else's code in this repository. I know that Linus Torvalds thinks I'm a moron for liking RCS/CVS/SVN, but at least I don't have to act like Linus Torvalds riding herd over thousands of files, dispensing life and death to every pull request.

I just want my little change to go to my little spot in my little github account. Then, if I like my change, I would like to be able to hand it to you.

These other changes that I got infected with are supposedly ahead of your branch. I don't know how I can import PR changes from your repo before you merge them into your repo. If you want to reject this PR, I very much do understand.

--Jared

**Comment by jaredor** [comment]
Clicked "Close with comment" instead of "Comment" Sorry. I thought I was closing the comment itself. I didn't think I was closing the PR. I really need to drink the github Kool-aid.

**Comment by manwar** [comment]
Sorry for the trouble. Let me see if it is OK. I will sort out, don't worry. Thanks for your contributions. @jaredor

**Comment by jaredor** [comment]
> 
> 
> Sorry for the trouble. Let me see if it is OK. I will sort out, don't worry. Thanks for your contributions. @jaredor
> 
> EDIT: just checked, all good. You did it in the end. Well done.

Manwar, just a note to say that I think you are doing a great job. Thanks for producing The Weekly Challenge.

**Pull request merged**
