### PR TITLE
add POD for usage and description

### PR DESCRIPTION
**Pull request by jeongoon**

### CODE REVIEW

**Comment by manwar** [comment]
This is very useful, thanks @jeongoon

**Comment by manwar** [comment]
Hi @jeongoon,

I have small a request, can you please share short introduction of yourself optionally with photo, to be included in the weekly newsletter to perlweeklychallenge@yahoo.com.

Many Thanks.
Best Regards,
Mohammad

**Comment by jeongoon** [comment]
Oh, Hi.
I'm a japanese chef in Sydney, Australia. I used to write some tiny codes in Perl since 2002 to 2015
they are only for personal study and curiosity.
and there are not so much  about talking my background but I love free software and GNU/Linux.
and use them everyday.
Thank you for making great opportunity to share all the code and
I hope I could contribute in some way to keep the community grows. It was very fun.

Myoungjin Jeon

**Comment by manwar** [comment]
> Oh, Hi.
> I'm a japanese chef in Sydney, Australia. I used to write some tiny codes in Perl since 2002 to 2015
> they are only for personal study and curiosity.
> and there are not so much about talking my background but I love free software and GNU/Linux.
> and use them everyday.
> Thank you for making great opportunity to share all the code and
> I hope I could contribute in some way to keep the community grows. It was very fun.
> 
> Myoungjin Jeon

Thanks @jeongoon for sharing your details.

**Pull request merged**
