### PR TITLE
Java solution for the pattern match

### PR DESCRIPTION
**Pull request by ziameraj16**

### CODE REVIEW

**Comment by xkr47** [comment]
Hi, just noticed that Task #1 asked for a wildcard pattern match, not a regular expression pattern match that you have..

**Comment by ziameraj16** [comment]
Good point, Will `?` be considered a wildcard as well?

**Comment by xkr47** [comment]
As defined in the task, `*` and `?` are the only wildcards.

**Comment by manwar** [comment]
Thanks @ziameraj16

**Pull request merged**
